logging:
  level:
    com:
      daitda:
        backend: DEBUG
    org:
      springframework: ERROR

server:
  address: localhost
  port: 8080

spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://daitda.ckgxusuue8oz.ap-northeast-2.rds.amazonaws.com:3306/daitda
    username: youngbeom0908
    password: Vmfkdl99!!

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB53Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true

